// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAIP3171zRn90VlgKUAJBUnR6l5imlFFc',
    appId: '1:721972208500:web:db41a17b25312bfeac4221',
    messagingSenderId: '721972208500',
    projectId: 'petcare-a7-plus-2026-d7623',
    authDomain: 'petcare-a7-plus-2026-d7623.firebaseapp.com',
    storageBucket: 'petcare-a7-plus-2026-d7623.firebasestorage.app',
    measurementId: 'G-CGVTB8ZVYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWVIrT1s6cleeCb6wQcWCidGOEnZQfKiU',
    appId: '1:721972208500:android:5cdd066baee960deac4221',
    messagingSenderId: '721972208500',
    projectId: 'petcare-a7-plus-2026-d7623',
    storageBucket: 'petcare-a7-plus-2026-d7623.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaxUIz1H3ht2_MRDm6zfTrmLjAOorbhMA',
    appId: '1:721972208500:ios:1db7b6264d47ebf6ac4221',
    messagingSenderId: '721972208500',
    projectId: 'petcare-a7-plus-2026-d7623',
    storageBucket: 'petcare-a7-plus-2026-d7623.firebasestorage.app',
    iosClientId: '721972208500-5d7lklhtrgpp7t8s2ara30160i30o8v7.apps.googleusercontent.com',
    iosBundleId: 'com.example.petCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaxUIz1H3ht2_MRDm6zfTrmLjAOorbhMA',
    appId: '1:721972208500:ios:1db7b6264d47ebf6ac4221',
    messagingSenderId: '721972208500',
    projectId: 'petcare-a7-plus-2026-d7623',
    storageBucket: 'petcare-a7-plus-2026-d7623.firebasestorage.app',
    iosClientId: '721972208500-5d7lklhtrgpp7t8s2ara30160i30o8v7.apps.googleusercontent.com',
    iosBundleId: 'com.example.petCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAIP3171zRn90VlgKUAJBUnR6l5imlFFc',
    appId: '1:721972208500:web:4e414713c24eafa8ac4221',
    messagingSenderId: '721972208500',
    projectId: 'petcare-a7-plus-2026-d7623',
    authDomain: 'petcare-a7-plus-2026-d7623.firebaseapp.com',
    storageBucket: 'petcare-a7-plus-2026-d7623.firebasestorage.app',
    measurementId: 'G-4BTHY3T7Z0',
  );
}
